portfolio-project-matching-app/components/ProjectCard.js
portfolio-project-matching-app/components/UserIcon.js
portfolio-project-matching-app/pages/test_projectCardPage.js
portfolio-project-matching-app/styles/globals.css
portfolio-project-matching-app/tailwind.config.js

basic ProjectCard Component skeleton. I did not want to go too crazy styling this thing out, because I don't have the greatest idea of context (as we discussed a bit in Slack). The component should be fairly responsive and is available for demonstration at localhost:3000/test_projectCardPage.
I had to fiddle with margin a bit, because the Button component has margin 'built-in' and was causing some alignment issues.

Feature project card component

---

portfolio-project-matching-app/components/Login.js
portfolio-project-matching-app/pages/test_loginPage.js
portfolio-project-matching-app/styles/globals.css

Created Login component:
- Utilizes Button and Input components created by teammates.
- Link at the bottom to toggle over to the Signup component.
- If we decide to do so, we can have a dual login/signup component, but I thought it might be better to separate duties into dedicated components.
- Still noticing some slight issues arising from our small components having margin requirements. This ends up throwing off the alignment with their siblings. We may want to discuss placing the burden of padding on the parent element.
- Once again, I've included a test page, but I would be happy to remove these going forward.
- I chose to fix the width of the component, because several of the examples I saw online chose that approach. We can absolutely change this if the team would like to do so.

Feature login component

---

portfolio-project-matching-app/components/InputDropdown.js
portfolio-project-matching-app/pages/test_inputDropdownPage.js

Created a drop-down input:
- Inspiration was the need to gather timezone information from user at signup. Could be helpful elsewhere.
- Stole most of the styling inspiration from Charlie's input.
- We may consider bringing in the `react-select` package to style this component further. It appears naked CSS can only do so much.
- I refrained from adding any margin due to the issues I was having with that when incorporating into forms.
- Left the bottom of the field "un-rounded". When the drop-down appears, it is not rounded and appears a bit awkward.

Feature InputDropDown Component

---

portfolio-project-matching-app/components/Button.js
portfolio-project-matching-app/components/Nav.js
portfolio-project-matching-app/components/Nav.module.css
portfolio-project-matching-app/pages/myProfile.js
portfolio-project-matching-app/pages/test_Nav.js

Resolves #16 
Makes Nav component.
On Profile page it shows "Browse" button on the right part of the nav bar. On every other page it shows the "Profile" button.

Nav Bar Resolves #16

---

portfolio-project-matching-app/components/Input.js
portfolio-project-matching-app/components/InputDropdown.js
portfolio-project-matching-app/components/Signup.js
portfolio-project-matching-app/pages/test_loginPage.js

Produced skeleton for the Signup component:
- Alignment is wacky due to margin inherent in the Button/Input components.
- Basic validation done on password and passwordRepeat.
- Will need major TLC with regards to authentication, didn't want to go to far on the DB component until we have Firebase fully up-and-running.
- Made very slight changes to the Input component. I found the need for an onChange prop and added this to the component. I realize this was the inappropriate branch to do this in.
- Further password validation is required, but did not want to work on this until Firebase Auth was ready.
- On successful form submission, the input values should clear. I will need to add a `value` prop to our Input component to get this working.
- SUMMARY: several stones left un-turned, but …

Feature Signup Component resolves #14

---

portfolio-project-matching-app/components/Button.module.css

Removed padding from Button component in favor of placing that burden on the parent element.

Enhancement Button Responsiveness resolves #25

---

portfolio-project-matching-app/components/Input.js
portfolio-project-matching-app/components/Input.module.css
portfolio-project-matching-app/components/Search.js
portfolio-project-matching-app/pages/test_searchPage.js

Created responsive search component, inspired by Josh's BrowseProjects wireframe:
- Input portion of component should grow/shrink according to parent width requirements.
- Made changes to `Input.module.css` to align with pull request that makes the Input component a bit more responsive in terms of width.
Wider width constraints
Smaller width constraints

Feature search component resolves #21

---

portfolio-project-matching-app/components/Input.module.css
portfolio-project-matching-app/components/Login.js
portfolio-project-matching-app/components/Signup.js
portfolio-project-matching-app/pages/test_loginPage.js

Made changes to `Input.js` in an attempt to improve responsiveness:
- Removed margin from `input.module.css` in favor of placing this burden on the parent element.
- Changed width specification to `w-full`, which translates to 100% width in naked CSS.
- Made slight changes to dependent components `Signup.js` and `Login.js`. I had alluded to these changes being needed once the leaf component was tweaked.

Enhancement Input Responsiveness resolves #22

---

portfolio-project-matching-app/models/Project.js

Resolves the typo mentioned in #48

Update Project.js to fix typo

---

portfolio-project-matching-app/pages/project.js

Creates the individual project page.
The path uses query parameters to get information about a project. Example path `/project?id=6AqEuYkqrsArfuUEIOCQ`
It still needs more styling and responsiveness. The "like" and "join" buttons are not functional.

View project

---

portfolio-project-matching-app/components/MultipleInputDropdown.js
portfolio-project-matching-app/components/MultipleInputDropdown.module.css
portfolio-project-matching-app/components/ProfileForm.js
portfolio-project-matching-app/package-lock.json
portfolio-project-matching-app/package.json
portfolio-project-matching-app/pages/newProject.js

This Pull Request adds the `MultipleInputDropdown` component. Using the [react-select](https://react-select.com/home) library lets us have a dropdown which allows users to select multiple items, search items in the dropdown, remove a specific item, and clear all items. 
The styling is definitely in draft phase. I also updated the `myProfile` page to have styles that are more in line with the `newProject` page. We can change these styles, I just think there should be consistency. 
Here is a screenshot of the `newProject` page form with the updated dropdown menu:
Here is a screenshot of the `myProfile` page form with the updated dropdown menu:

Multiple Input Dropdown Component

---

portfolio-project-matching-app/components/ProjectCard.js

Adds a "View More Info" button to the project card.
If you click the "View More Info" button it will take you to the dedicated page for that project (`/project?id=project_id`)

Add "View More Info" button to ProjectCards

---

portfolio-project-matching-app/pages/index.js

Redirects '/' to '/browseProjects'

Home redirect

---

portfolio-project-matching-app/backend/dao.js
portfolio-project-matching-app/components/FilterButtons.js
portfolio-project-matching-app/components/ProjectCard.js
portfolio-project-matching-app/models/Project.js
portfolio-project-matching-app/pages/browseProjects.js

`FilterButtons` component should interact with `browseProjects` as expected:
- I realize that the work comes across a bit messy. I had several steps where I should have taken a deep breath and refactored/modularized things a bit. Felt the pressure of tomorrow's deadline, but have several ideas re: modularization e.g., moving a few things into class methods.

Feature browseProjects Page

---

portfolio-project-matching-app/pages/browseProjects.js

Adds the ability to search projects by name using the search input on browseProjects page.

Search Projects

---

portfolio-project-matching-app/models/FilteredProject.js
portfolio-project-matching-app/models/Project.js
portfolio-project-matching-app/pages/browseProjects.js

This fix should prevent errors when user switches pages while state is `async` functions in `useEffect` are still fetching and setting state. Also, the search bar and filter buttons should work in harmony.

Enhancement browse filter search orchestration

---

portfolio-project-matching-app/Firebase/auth.js
portfolio-project-matching-app/Firebase/clientApp.ts
portfolio-project-matching-app/backend/dao.js
portfolio-project-matching-app/backend/daoUser.js
portfolio-project-matching-app/components/Nav.js
portfolio-project-matching-app/components/NewLogin.js
portfolio-project-matching-app/components/ProfileForm.js
portfolio-project-matching-app/context/AuthContext.js

Lots of big changes here.
- Allows user to stay signed in across refreshes.
- Nav bar shows "Sign In" instead of "Profile" if user is not signed in.
- New users are added to the user collection in Firestore.
- User can update their profile from the profile page. (but not projects or technologies yet)
- Changes to how users are modeled:
Authenticated User:
```
{"user": {
"id":"1gzziJKCpTTtuIy1UnZuBKEqsYz2",
"email":"josh.j.kaiser@gmail.com",
"username":"josh.j.kaiser@gmail.com",
"introduction":"Hi, I'm Josh Kaiser and I like to code every second of every day every day of every year",
"projects":[],
"technologies":[]
}
}
```
No Authenticated User:
```
{"user": null}
```
- To use auth value in your page.
```JavaScript
import { useAuth } from '../context/AuthContext';
// In your functional …
```

Auth db interaction

---

portfolio-project-matching-app/__mocks__/fileMock.js
portfolio-project-matching-app/__mocks__/styleMock.js
portfolio-project-matching-app/__tests__/dummy.test.js
portfolio-project-matching-app/jest.config.js
portfolio-project-matching-app/package-lock.json
portfolio-project-matching-app/package.json
portfolio-project-matching-app/pages/test_dao.js

Installed Jest and created directories and config file per Jest/Next.js documentation

Enhancement testing

---

portfolio-project-matching-app/Firebase/auth.js
portfolio-project-matching-app/components/Nav.js
portfolio-project-matching-app/components/NewLogin.js
portfolio-project-matching-app/pages/signUp.js

- Creates separate sign in and sign up pages.
- Notifies the user on errors with sign up and sign in.

New sign in options

---

portfolio-project-matching-app/backend/dao.js
portfolio-project-matching-app/backend/daoUser.js
portfolio-project-matching-app/components/ProjectCard.js
portfolio-project-matching-app/pages/browseProjects.js
portfolio-project-matching-app/pages/myProfile.js
portfolio-project-matching-app/pages/myProjects.js
portfolio-project-matching-app/pages/test_dao.js

Connected `ProjectCard` `join` button to a meaningful function that creates the association between the current user and the project. Also, created a `myProjects` page, mostly for development purposes, but we might incorporate something similar at some point.

Enhancement `join` and `myProjects`

---

portfolio-project-matching-app/backend/dao.js
portfolio-project-matching-app/pages/test_dao.js

Created one-stop-shop for deleting a document and all of it's association documents via `deleteDocAndAssociations(coll, id)`. This should be helpful during development and also will reduce code if a document "owner" chooses to delete it.

Enhancement-`deleteDocAndAssociations()`

---

portfolio-project-matching-app/backend/dao.js
portfolio-project-matching-app/pages/test_dao.js

- Offloaded some work from the main functions into descriptive helper functions to improve readability.
- Some functions were calling several independent asynchronous functions in a row and requiring that they `await` their neighbors resolve. However, given that they are independent, it was best to have them do their fetching simultaneously and instruct the remainder of the function to `await` their collective resolve. This was a great suggestion by Josh.

Enhancement `dao.js` tidying

---

portfolio-project-matching-app/backend/dao.js
portfolio-project-matching-app/pages/newProject.js
portfolio-project-matching-app/pages/test_dao.js

The form on the `newProject` page should create a new project document along with the technology association from the multi-select input and the implied user (owner).

Enhancement `newProject` integration

---

portfolio-project-matching-app/components/Button.module.css
portfolio-project-matching-app/components/Input.module.css
portfolio-project-matching-app/components/Nav.js
portfolio-project-matching-app/components/Nav.module.css
portfolio-project-matching-app/components/ProfileForm.js
portfolio-project-matching-app/components/ProjectCard.js
portfolio-project-matching-app/components/ProjectCard.module.css
portfolio-project-matching-app/components/Search.js
portfolio-project-matching-app/components/Textarea.js
portfolio-project-matching-app/pages/browseProjects.js
portfolio-project-matching-app/pages/newProject.js
portfolio-project-matching-app/pages/project.js
portfolio-project-matching-app/styles/globals.css
portfolio-project-matching-app/tailwind.config.js

Adds styling to Components based on [Color Palette](https://coolors.co/001219-005f73-0a9396-94d2bd-e9d8a6-ee9b00-ca6702-bb3e03-ae2012-9b2226).
Still need to make changes for mobile compatibility.

Enhancement design updates

---

portfolio-project-matching-app/backend/daoProject.js
portfolio-project-matching-app/backend/daoUser.js

Leveraged `await Promise.all()` in speeding up load times for the `browseProjects` page.

Enhancement / Bug - `dao.js` `await Promise.all()`

---

portfolio-project-matching-app/backend/dao.js
portfolio-project-matching-app/models/Application.js
portfolio-project-matching-app/models/FilteredApplication.js
portfolio-project-matching-app/models/FilteredProject.js
portfolio-project-matching-app/pages/myApplications.js

Added the ability to filter application similar to what we did with the `browseProjects` page. Things are a bit messy right now, but I plan to tighten things up during the coming sprint.

Enhancement `myApplications` filtering

---

portfolio-project-matching-app/Firebase/auth.js
portfolio-project-matching-app/backend/dao.js
portfolio-project-matching-app/backend/daoProject.js
portfolio-project-matching-app/backend/daoUser.js
portfolio-project-matching-app/components/ApplicationCard.js
portfolio-project-matching-app/components/Button.module.css
portfolio-project-matching-app/components/Input.module.css
portfolio-project-matching-app/components/Nav.js
portfolio-project-matching-app/components/Nav.module.css
portfolio-project-matching-app/components/NewLogin.js
portfolio-project-matching-app/components/ProfileForm.js
portfolio-project-matching-app/components/ProjectCard.js
portfolio-project-matching-app/components/ProjectCard.module.css
portfolio-project-matching-app/components/Search.js
portfolio-project-matching-app/components/Textarea.js
portfolio-project-matching-app/models/Application.js
portfolio-project-matching-app/models/FilteredApplication.js
portfolio-project-matching-app/models/FilteredProject.js
portfolio-project-matching-app/package-lock.json
portfolio-project-matching-app/package.json
portfolio-project-matching-app/pages/browseProjects.js
portfolio-project-matching-app/pages/myApplications.js
portfolio-project-matching-app/pages/myProfile.js
portfolio-project-matching-app/pages/myProjects.js
portfolio-project-matching-app/pages/newProject.js
portfolio-project-matching-app/pages/project.js
portfolio-project-matching-app/pages/signUp.js
portfolio-project-matching-app/pages/test_dao.js
portfolio-project-matching-app/styles/globals.css
portfolio-project-matching-app/tailwind.config.js

`Sprint-5` -> `main`

---

portfolio-project-matching-app/pages/newProject.js
portfolio-project-matching-app/pages/test_dao.js

Fixed a few bugs in the `newProject` page:
- capacity field was being created as a string, converted form value to integer
- likes was not being added to the payload, manifesting in the absence of the likes field in Firebase (fixed this)
- census was being initialized as 1, but then incremented when the `projects_users` association was created (fixed it)

Enhancement / Bug - `newProject`

---

portfolio-project-matching-app/backend/dao.js
portfolio-project-matching-app/components/ProjectCard.js
portfolio-project-matching-app/pages/browseProjects.js

Leveraged Charlie's work in adding the like/dislike feature to `ProjectCard`.

Feature `like` and `dislike` project

---

portfolio-project-matching-app/Firebase/auth.js
portfolio-project-matching-app/__tests__/ApplicationCard.test.js
portfolio-project-matching-app/__tests__/FilterButtons.test.js
portfolio-project-matching-app/__tests__/ProjectCard.test.js
portfolio-project-matching-app/__tests__/browseProjects.test.js
portfolio-project-matching-app/__tests__/dummy.test.js
portfolio-project-matching-app/backend/dao.js
portfolio-project-matching-app/backend/daoProject.js
portfolio-project-matching-app/backend/daoTechnology.js
portfolio-project-matching-app/backend/daoUser.js
portfolio-project-matching-app/components/ApplicationCard.js
portfolio-project-matching-app/components/FilterButtons.js
portfolio-project-matching-app/components/Nav.js
portfolio-project-matching-app/components/ProjectCard.js
portfolio-project-matching-app/context/AuthContext.js
portfolio-project-matching-app/package-lock.json
portfolio-project-matching-app/package.json
portfolio-project-matching-app/pages/browseProjects.js
portfolio-project-matching-app/pages/myApplications.js
portfolio-project-matching-app/pages/myProjects.js
portfolio-project-matching-app/pages/newProject.js
portfolio-project-matching-app/pages/project.js
portfolio-project-matching-app/pages/test_dao.js

`Sprint-6` -> `main`

---

portfolio-project-matching-app/models/Projects.js
portfolio-project-matching-app/pages/browseProjects.js

Moved the heavy lifting resulting from the filtering functionality into a `Projects` object

Enhancement `browseProjects` Filter Optimization

---

portfolio-project-matching-app/backend/dao.js
portfolio-project-matching-app/components/MultipleInputDropdown.js
portfolio-project-matching-app/components/ProfileForm.js

Josh Kaiser is responsible for virtually all the work done on this PR
- the `profileForm` `MultiInputDrowdown` populates with the user's current associated technologies
- changes made to associated technologies should persist and appear in the form

Enhancement `myProfile` technologies
